config/routes.rb
Rails.application.routes.draw do
  get 'feed' => 'epicenter#feed'
  get 'show_user' => 'epicenter#show_user'
  get 'now_following' => 'epicenter#now_following'
  get 'unfollow' => 'epicenter#unfollow'
  get 'following' => 'epicenter#following'
  get 'followers' => 'epicenter#followers'
  get 'add' => 'epicenter#add_book'
  get 'remove' => 'epicenter#remove_book'
  get 'user_books' => 'epicenter#user_books'
  get 'your_books' => 'epicenter#your_books'
  get 'shared_books' => 'epicenter#shared_books'
  get 'your_ratings' => 'epicenter#your_ratings'
  get 'recommended' => 'epicenter#recommended'
  get 'like' => 'epicenter#like'
  get 'dislike' => 'epicenter#dislike'


  get 'books' => 'books#index'
  get 'show_book' => 'books#show'
  get 'new_book' => 'books#new'

  get 'index' => 'posts#index'
  get 'new' => 'posts#new'

  root 'epicenter#feed'

  get 'all_users' => 'posts#users'

  resources :posts
  resources :books
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
	has_many :users
	validates :title, presence: true, uniqueness: true
	validates :author, presence: true
	serialize :likes, Array
	serialize :dislikes, Array
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :all_books, only: [:index, :create]
	before_action :set_book, only: [:show, :edit, :update, :destroy]

	def index
		@books = Book.all
	end
	def show
		@number_of_likes = 0
    @number_of_votes = 0

    @liked_by = []
    @disliked_by = []

    User.all.each do |user|
      if user.liked_books.include?(@book.id)
        @number_of_likes += 1
        @number_of_votes += 1
      elsif user.disliked_books.include?(@book.id)
        @number_of_votes += 1
      end

      if @book.likes.include?(user.id)
        @liked_by.push(user)
        @disliked_by.delete(user)
      elsif @book.dislikes.include?(user.id)
        @disliked_by.push(user)
        @liked_by.delete(user)
      end
    end
	end
	def new
		@book = Book.new
	end
  	def create
    	# @book = Book.new(book_params)
			@book = Book.create(book_params)
  	end
  	def update
    	respond_to do |format|
      		if @book.update(book_params)
        		format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        		format.json { render :show, status: :ok, location: @book }
      		else
        		format.html { render :edit }
        		format.json { render json: @book.errors, status: :unprocessable_entity }
      		end
    	end
  	end
  	def destroy
    	@book.destroy
    	respond_to do |format|
      		format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      		format.json { head :no_content }
    	end
  	end
  private
    # Use callbacks to share common setup or constraints between actions.
		def all_books
			@books = Book.all
		end
		def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :page_length)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class="col-xs-3">
  <div class="book">
  <h3><%= link_to book.title, show_book_path(id: book.id) %></h3>
  <h5><%= book.author %></h5>
  <p>Length: <%= book.page_length %> pages</p>
  <p>
  <% if user_signed_in? %>
    <% if current_user.book_list.include?(book.id) %>
      <%= link_to "Remove", remove_path(id: book.id), class: "btn btn-danger following" %>
    <% else %>
      <%= link_to "Add", add_path(id: book.id), class: "btn btn-primary following" %>
    <% end %>
  <% end %>
  </p>
  <%= link_to 'Show', book %>
  <%= link_to 'Edit', edit_book_path(book) %>
  <%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_with(model: @book, remote: true) do |form| %>

  <div class="form-group">
    <%= form.text_field :title, placeholder: "Title", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.text_field :author, placeholder: "Author", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :page_length %>
    <%= form.number_field :page_length %>
  </div>

<div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/books/create.js.erb
$('#books').html("<%= j (render @books) %>");
$('#book-form').slideUp(350);

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<center><h1>Books</h1></center>
<center><%= link_to 'New Book', new_book_path, remote: true, class: "btn btn-primary" %></center>
<div class="new-book" id="book-form" style="display:none;"></div>
<div class="row">
  <div id="books">
    <%= render @books %>
  </div>
</div>

app/views/books/new.js.erb
$('#book-form').html("<%= j (render 'form') %>");
$('#book-form').slideDown(350);

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
<div class="row">
<div class="col-xs-4">

<div class="book">
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Page length:</strong>
  <%= @book.page_length %>
</p>

<p>
  <strong>Rating:</strong>
  <% if @number_of_votes == 0 %>
    No votes yet
  <% else %>
    <%= (@number_of_likes.to_f / @number_of_votes.to_f) * 100 %>% from <%= @number_of_votes %> votes.
  <% end %>
</p>

<p>
    <% if user_signed_in? %>
    <% if current_user.book_list.include?(@book.id) %>
        <%= link_to "Remove", remove_path(id: @book.id), class: "btn btn-danger following" %>
    <% else %>
	    <%= link_to "Add", add_path(id: @book.id), class: "btn btn-primary following" %>
    <% end %>
    <% end %>
</p>
<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>
</div>

</div>
<div class="col-xs-4">
<center><h2>Users who like this book</h2></center>
<center>
  <% if @liked_by.empty? %>
  <h3 class="user">None</h3>
  <% end %>
</center>
<% @liked_by.each do |user| %>
  <div class="user">
  <%= link_to "@#{user.username}", show_user_path(id: user.id) %>
  <div class="pull-right">
  <% if user_signed_in? %>
    <% if current_user.following.include?(user.id) %>
        <%= link_to "Unfollow", unfollow_path(id: user.id), class: "btn btn-danger following" %>
    <% elsif current_user.id != user.id %>
        <%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary following" %>
    <% end %>
  <% end %>
  </div>
  </div>
  <br>
<% end %>
</div>

<div class="col-xs-4">
<center><h2>Users who dislike this book</h2></center>
<center>
  <% if @disliked_by.empty? %>
  <h3 class="user">None</h3>
  <% end %>
</center>
<% @disliked_by.each do |user| %>
  <div class="user">
  <%= link_to "@#{user.username}", show_user_path(id: user.id) %>
  <div class="pull-right">
  <% if user_signed_in? %>
    <% if current_user.following.include?(user.id) %>
        <%= link_to "Unfollow", unfollow_path(id: user.id), remote: true, class: "btn btn-danger following" %>
    <% elsif current_user.id != user.id %>
        <%= link_to "Follow", now_following_path(id: user.id), remote: true, class: "btn btn-primary following" %>
    <% end %>
  <% end %>
  </div>
  </div>
  <br>
<% end %>
</div>

</div>

</div>