config/routes.rb
Rails.application.routes.draw do
  get 'feed' => 'epicenter#feed'
  get 'show_user' => 'epicenter#show_user'
  get 'now_following' => 'epicenter#now_following'
  get 'unfollow' => 'epicenter#unfollow'
  get 'following' => 'epicenter#following'
  get 'followers' => 'epicenter#followers'
  get 'add' => 'epicenter#add_book'
  get 'remove' => 'epicenter#remove_book'
  get 'user_books' => 'epicenter#user_books'
  get 'your_books' => 'epicenter#your_books'
  get 'shared_books' => 'epicenter#shared_books'
  get 'your_ratings' => 'epicenter#your_ratings'
  get 'recommended' => 'epicenter#recommended'
  get 'like' => 'epicenter#like'
  get 'dislike' => 'epicenter#dislike'


  get 'books' => 'books#index'
  get 'show_book' => 'books#show'
  get 'new_book' => 'books#new'

  get 'index' => 'posts#index'
  get 'new' => 'posts#new'

  root 'epicenter#feed'

  get 'all_users' => 'posts#users'

  resources :posts
  resources :books
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  def feed
    if user_signed_in?
      @following_posts = []

  	  Post.all.each do |post|
  		  if current_user.following.include?(post.user_id) || current_user.id == post.user_id
  			   @following_posts.push(post)
  		  end
  	 end
    else
      redirect_to index_path
    end
    @posts = @following_posts
  end

  def show_user
    @user = User.find(params[:id])
    @shared_books_number = 0

    Book.all.each do |book|
      if @user.book_list.include?(book.id) && current_user.book_list.include?(book.id)
        @shared_books_number += 1
      end
    end

    @book = "book"
    if @shared_books_number != 1
      @book = "books"
    end
  end

  def recommended
    @following = []
    User.all.each do |user|
      if current_user.following.include?(user.id)
        @following.push(user)
      end
    end

    @recommended = []
    Book.all.each do |book|
      if current_user.book_list.include?(book.id) == false
        @following.each do |user|
          if user.liked_books.include?(book.id)
            @recommended.push(book)
          end
        end
      end
    end
  end

  def your_ratings
    @liked_books = []
    @disliked_books = []

    Book.all.each do |book|
      if current_user.liked_books.include?(book.id)
        @liked_books.push(book)
      end
      if current_user.disliked_books.include?(book.id)
        @disliked_books.push(book)
      end
    end
  end

  def like
    current_user.disliked_books.delete(params[:id].to_i)
    current_user.liked_books.push(params[:id].to_i)
    current_user.save
    Book.all.each do |book|
      if current_user.liked_books.include?(book.id)
        book.dislikes.delete(current_user.id)
        book.likes.push(current_user.id.to_i)
      end
      book.save
    end

    redirect_back(fallback_location: root_path)
  end

  def dislike
    current_user.liked_books.delete(params[:id].to_i)
    current_user.disliked_books.push(params[:id].to_i)
    current_user.save
    Book.all.each do |book|
      if current_user.disliked_books.include?(book.id)
        book.likes.delete(current_user.id)
        book.dislikes.push(current_user.id.to_i)
      end
      book.save
    end

    redirect_back(fallback_location: root_path)
  end

  def now_following
    current_user.following.push(params[:id].to_i)
    current_user.save

    redirect_back(fallback_location: root_path)
  end

  def unfollow
    current_user.following.delete(params[:id].to_i)
    current_user.save

    redirect_back(fallback_location: root_path)
  end

  def following
    @user = User.find(params[:id])
    @following = []
    User.all.each do |user|
      if @user.following.include?(user.id)
        @following.push(user)
      end
    end
  end
  def followers
    @user = User.find(params[:id])
    @followers = []
    User.all.each do |user|
      if user.following.include?(@user.id)
        @followers.push(user)
      end
    end
  end

  def your_books
    @book_list =[]
    Book.all.each do |book|
      if current_user.book_list.include?(book.id)
        @book_list.push(book)
      end
    end
  end

  def user_books
    @user = User.find(params[:id])
    if @user.id == current_user.id
      redirect_to your_books_path(id: current_user.id)
    end

    @book_list = []

    Book.all.each do |book|
      if @user.book_list.include?(book.id)
        @book_list.push(book)
      end
    end
  end

  def shared_books
    @user = User.find(params[:id])
    @shared_books = []

    Book.all.each do |book|
      if @user.book_list.include?(book.id) && current_user.book_list.include?(book.id)
        @shared_books.push(book)
      end
    end
  end

  def add_book
    current_user.book_list.push(params[:id].to_i)
    current_user.save

    redirect_back(fallback_location: root_path)
  end

  def remove_book
    current_user.book_list.delete(params[:id].to_i)
    current_user.save

    redirect_back(fallback_location: root_path)
  end
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/views/epicenter/add_book.html.erb
<!-- Adds a book to a user's booklist. -->

app/views/epicenter/feed.html.erb
<div>
	<% if user_signed_in? %>
		<% if current_user.following.empty? %>
    		<center><h3>You're not following anyone! Take a look at the General Feed <%= link_to 'Here', index_path, class: "btn btn-default" %></h3></center>
    <% end %>
		<% if user_signed_in? %>
			<div class="feed">
				<h1>
					Your Feed
					<%= link_to "All Posts", index_path, class: "btn btn-default pull-right" %>
				</h1>
				<% if @following_posts.empty? %>
					<h2 class="post">Nothing to see here</h2>
				<% end %>
				<% if user_signed_in? %>
					<%= link_to 'New Post', new_post_path, remote: true, class: "btn btn-primary" %>
					<div id="post-form" style="display:none;"></div>
				<% end %>
				<div id="posts">
			  	<%= render @posts %>
				</div>
			</div>
		<% end %>
	<% end %>
</div>

app/views/epicenter/followers.html.erb
<% @followers.each do |user| %>
<div class="user">
<div class="row">
<div class="col-xs-6">
	<h4 class="pull-left"><%= link_to user.username, show_user_path(id: user.id), class: "following" %></h4>
</div>
<div class="col-xs-6">
	<span class="pull-right">
   	<% if user_signed_in? %>
    	<% unless current_user.id == user.id %>
    	<% if current_user.following.include?(user.id) %>
    		<%= link_to "Unfollow", unfollow_path(id: user.id), remote: true, class: "btn btn-danger following" %>
    	<% else %>
       		<%= link_to "Follow", now_following_path(id: user.id), remote: true, class: "btn btn-primary following" %>
    	<% end %>
    	<% end %>
    <% end %>
	</span>
</div>
</div>
</div>
<br>
<% end %>

app/views/epicenter/following.html.erb
<% @following.each do |user| %>
<div class="user">
<div class="row">
<div class="col-xs-6">
	<h4 class="pull-left"><%= link_to user.username, show_user_path(id: user.id), class: "following" %></h4>
</div>
<div class="col-xs-6">
	<span class="pull-right">
   	<% if user_signed_in? %>
    	<% unless current_user.id == user.id %>
    	<% if current_user.following.include?(user.id) %>
    		<%= link_to "Unfollow", unfollow_path(id: user.id), remote: true, class: "btn btn-danger following" %>
    	<% else %>
       		<%= link_to "Follow", now_following_path(id: user.id), remote: true, class: "btn btn-primary following" %>
    	<% end %>
    	<% end %>
    <% end %>
	</span>
</div>
</div>
</div>
<br>
<% end %>

app/views/epicenter/recommended.html.erb
<h1>Recommended For You</h1>
<h3>These are books that you haven't read and that were liked by people you follow. Check them out!</h3>
<div class="row">
	<% @recommended.each do |book| %>
		<div class="col-xs-3">
		<div class="book">
			<h3><%= link_to book.title, show_book_path(id: book.id) %></h3>
			<%= link_to "Add", add_path(id: book.id), remote: true, class: "btn btn-primary following pull-right" %>
			<h5><%= book.author %></h5>
		</div>
		</div>
	<% end %>
</div>

app/views/epicenter/remove_book.html.erb
<!-- Removes a book from the user's booklist. -->

app/views/epicenter/shared_books.html.erb
<h1>Here are the books you share with @<%= @user.username %></h1>
<% @shared_books.each do |book| %>
	<div class="book">
	<h3><%= link_to book.title, show_book_path(id: book.id) %></h3>
	<h5><%= book.author %></h5>
	</div>
	<br>
<% end %>

app/views/epicenter/show_user.html.erb
<center>
<% if @user.id == current_user.id %>
    <h1>Your Profile</h1>
<% else %>
    <h1>@<%= @user.username %>'s Profile</h1>
    <% if user_signed_in? %>
    <% if current_user.following.include?(@user.id) %>
        <p><%= link_to "Unfollow", unfollow_path(id: @user.id), remote: true, class: "btn btn-danger following" %></p>
    <% else %>
        <p><%= link_to "Follow", now_following_path(id: @user.id), remote: true, class: "btn btn-primary following" %></p>
    <% end %>
    <% end %>
<% end %>
</center>
<div class="bio">
<center><h3><%= @user.name %></h3></center>
<p><%= @user.bio %></p>
<div class="row">
    <div class="col-xs-6">
    <% if @user.id != current_user.id %>
        <h4>You share <%= @shared_books_number %> <%= @book %> with <%= "@#{@user.username}" %></h4>
        <p><%= link_to "Shared Books", shared_books_path(id: @user.id), class: "btn btn-default" %></p>
    <% end %>
    <p><%= link_to "@#{@user.username}'s Books", user_books_path(id: @user.id), class: "btn btn-default" %></p>
    </div>
    <div class="col-xs-6">
    <div class="pull-right">
    <%= link_to "Who @#{@user.username} Follows", following_path(id: @user.id), class: "btn btn-default" %>
    <br>
    <br>
    <%= link_to "@#{@user.username}'s Followers", followers_path(id: @user.id), class: "btn btn-default" %>
    </div>
    </div>
</div>

</div>
<br>
<div class="row">
<% @user.posts.each do |post| %>
    <div class="col-xs-6">
    <div class="post">
        <p><%= post.message %></p>
    </div>
    <br>
    <p>
        <% if user_signed_in? %>
            <% if current_user.id == post.user_id %>
                <%= link_to 'Edit', edit_post_path(post), class: "btn btn-default" %>
                <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            <% end %>
        <% end %>
    </p>
    <br>
    </div>
<% end %>
</div>

app/views/epicenter/user_books.html.erb
<% if @book_list.empty? %>
	<h2>No Books</h2>
<% end %>
<div class="row">
	<div id="books">
		<%= render @book_list %>
	</div>
</div>

app/views/epicenter/your_books.html.erb
<% if @book_list.empty? %>
	<h2>No Books</h2>
<% end %>
<h1>Rate Your books when you have finished reading them</h1>
<div class="row">
<% @book_list.each do |book| %>
	<div class="col-xs-4">
	<div class="book">
		<h3><%= link_to book.title, show_book_path(id: book.id) %></h3>
		<h5><%= book.author %></h5>
		<p><%= book.page_length %> pages</p>

    	<%= link_to "Remove", remove_path(id: book.id), class: "btn btn-danger following" %>
    	<div class="pull-right">
    	<% unless current_user.liked_books.include?(book.id) %>
    		<%= link_to "Like", like_path(id: book.id), remote: true, class: "btn btn-primary following" %>
    	<% end %>
    	<% unless current_user.disliked_books.include?(book.id) %>
    		<%= link_to "Dislike", dislike_path(id: book.id), remote: true, class: "btn btn-primary following" %>
    	<% end %>
    	</div>
    	<div class="pull-right">
		<% if current_user.liked_books.include?(book.id) %>
			<p class="like">You liked this book</p>
		<% elsif current_user.disliked_books.include?(book.id) %>
			<p class="like">You disliked this book</p>
		<% end %>
		</div>

	</div>
	<br>
	</div>
<% end %>
</div>

app/views/epicenter/your_ratings.html.erb
<center><h1>Your Ratings</h1></center>
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-6">
		<h3>Liked Books</h3>
		<% @liked_books.each do |book| %>
			<div class="book">
			<h3><%= link_to book.title, show_book_path(id: book.id) %></h3>
			<%= link_to "Dislike", dislike_path(id: book.id), remote: true, class: "btn btn-primary following pull-right" %>
			<p><%= book.author %></p>
			</div>
			<br>
		<% end %>
		</div>
		<div class="col-xs-6">
		<h3>Disliked Books</h3>
		<% @disliked_books.each do |book| %>
			<div class="book">
			<h3><%= book.title %></h3>
			<%= link_to "Like", like_path(id: book.id), remote: true, class: "btn btn-primary following pull-right" %>
			<p><%= book.author %></p>
			</div>
			<br>
		<% end %>
		</div>
	</div>
</div>