config/routes.rb
Rails.application.routes.draw do
  get 'feed' => 'epicenter#feed'
  get 'show_user' => 'epicenter#show_user'
  get 'now_following' => 'epicenter#now_following'
  get 'unfollow' => 'epicenter#unfollow'
  get 'following' => 'epicenter#following'
  get 'followers' => 'epicenter#followers'
  get 'add' => 'epicenter#add_book'
  get 'remove' => 'epicenter#remove_book'
  get 'user_books' => 'epicenter#user_books'
  get 'your_books' => 'epicenter#your_books'
  get 'shared_books' => 'epicenter#shared_books'
  get 'your_ratings' => 'epicenter#your_ratings'
  get 'recommended' => 'epicenter#recommended'
  get 'like' => 'epicenter#like'
  get 'dislike' => 'epicenter#dislike'


  get 'books' => 'books#index'
  get 'show_book' => 'books#show'
  get 'new_book' => 'books#new'

  get 'index' => 'posts#index'
  get 'new' => 'posts#new'

  root 'epicenter#feed'

  get 'all_users' => 'posts#users'

  resources :posts
  resources :books
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	validates :message, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :all_posts, only: [:index, :create]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  # GET /posts
  # GET /posts.json

  def users
    @users = User.all
  end

  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    # @post = Post.new(post_params)
    @post = Post.create(post_params)
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def all_posts
      @posts = Post.all
    end
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:message, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: @post, remote: true) do |form| %>

  <div class="form-group">
    <%= form.text_field :message, placeholder: "Your Post Here", class: "form-control post-field" %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
  <div class="post">
  <h3><%= link_to post.user.username, show_user_path(id: post.user_id) %></h3>
  <p><%= post.message %></p>
  <p>
    <% if user_signed_in? %>
    <% if current_user.id == post.user_id %>
    <%= link_to 'Edit', edit_post_path(post) %>
    <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    <% end %>
  </p>
  </div>
  <br>

app/views/posts/create.js.erb
$('#posts').html("<%= j (render @posts) %>");
$('#post-form').slideUp(350);

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if user_signed_in? == false %>
  <div>
    <h2>Please Create an Account or Log In to use this site</h2>
  </div>
  <%= link_to "Log In", new_user_session_path, class: "btn btn-default" %><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default" %>
<% end %>

<div class="feed">
  <h2>Posts</h2>
  <% if user_signed_in? %>
    <%= link_to 'New Post', new_post_path, remote: true, class: "btn btn-primary" %>
    <div id="post-form" style="display:none;"></div>
    <br>
  <% end %>
  <div id="posts">
    <%= render @posts %>
  </div>
</div>

app/views/posts/new.js.erb
$('#post-form').html("<%= j (render 'form') %>");
$('#post-form').slideDown(350);

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @post.message %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.username %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/users.html.erb
<h1>All Users</h1>
<div class="well">
<% @users.each do |user| %>
	<p><%= user.email %></p>
	<p><%= user.username %></p>
	<p><%= user.name %></p>
	<p><%= user.bio %></p>
	<p><%= user.id %></p>
<% end %>
</div>