config/routes.rb
Rails.application.routes.draw do
  get 'feed' => 'epicenter#feed'
  get 'show_user' => 'epicenter#show_user'
  get 'now_following' => 'epicenter#now_following'
  get 'unfollow' => 'epicenter#unfollow'
  get 'following' => 'epicenter#following'
  get 'followers' => 'epicenter#followers'
  get 'add' => 'epicenter#add_book'
  get 'remove' => 'epicenter#remove_book'
  get 'user_books' => 'epicenter#user_books'
  get 'your_books' => 'epicenter#your_books'
  get 'shared_books' => 'epicenter#shared_books'
  get 'your_ratings' => 'epicenter#your_ratings'
  get 'recommended' => 'epicenter#recommended'
  get 'like' => 'epicenter#like'
  get 'dislike' => 'epicenter#dislike'


  get 'books' => 'books#index'
  get 'show_book' => 'books#show'
  get 'new_book' => 'books#new'

  get 'index' => 'posts#index'
  get 'new' => 'posts#new'

  root 'epicenter#feed'

  get 'all_users' => 'posts#users'

  resources :posts
  resources :books
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <nav class="navbar navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", root_path, class: "nav-button" %></li>
          <!-- <li><%= link_to "New Post", new_post_path, class: "nav-button" %></li> -->
          <% if user_signed_in? %>
          <li class="dropdown">
              <a href="#" class="dropdown-toggle nav-button" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                Books<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "All Books", books_path %></li>
                <li><%= link_to "Your Books", your_books_path(id: current_user.id) %></li>
                <li><%= link_to "Your Ratings", your_ratings_path %></li>
                <li><%= link_to "Recommended Books", recommended_path %></li>
              </ul>
          <% else %>
            <li><%= link_to "All Books", books_path, class: "nav-button" %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle nav-button" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                @<%= current_user.username %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "My Profile", show_user_path(id: current_user.id) %></li>
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="body">
    <%= yield %>
  </div>
</body>
</html>